name: Windows RDP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Enable RDP
      run: |
        net user runneradmin P@ssw0rd123
        net localgroup administrators runneradmin /add
        netsh advfirewall set allprofiles state off

    - name: Download ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip

- name: Start RDP
  run: |
    .\ngrok\ngrok.exe authtoken $env:NGROK_AUTH_TOKEN
    Start-Process -NoNewWindow .\ngrok\ngrok.exe -ArgumentList "tcp 3389"
    timeout 21600
  env:
    NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
